version: '3'

services:
  next-app:
    container_name: na-rzf-next-app
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    environment:
      - UID=1000
      - GUID=1000
    user: '${UID}:${GID}'
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./:/app
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
