export enum LocalStorageKeys {
  REGION_SERVICE_ID = 'REGION_SERVICE_ID',
  CURRENT_TOWN = 'CURRENT_TOWN',
  TOWN_ID = 'TOWN_ID',
  TOWN_NAME = 'TOWN_NAME',
  REGION_GEOGRAPHIC_ID = 'REGION_GEOGRAPHIC_ID',
  REGION_GEOGRAPHIC_NAME = 'REGION_GEOGRAPHIC_NAME'
}
