import classNames from 'classnames'
import styles from './layout.module.css'
import Header from '@/components/Header/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames(styles['item'])}>
        <Header />
        {children}
      </body>
    </html>
  )
}
