version: '3'

services:
  next-app:
    container_name: na-rzf-next-app
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
    restart: always
    ports:
      - 127.0.0.1:3000:3000

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  default:
    external:
      name: my_network
